catalog:
  default:
    type: hive
    hive.metastore.uri: thrift://hive-metastore:9083
    warehouse: s3://warehouse/
    s3.endpoint: http://minio:9000
    s3.access-key-id: minioadmin
    s3.secret-access-key: minioadmin
